import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/context/ToastContext";
import { AuthProvider } from "@/context/AuthContext";
import { WalletProvider } from "@/context/WalletContext";
import { LoadingProvider } from "@/context/LoadingContext";
import { ThemeProvider } from "@/context/ThemeContext";
import { BreadcrumbProvider } from "@/context/BreadcrumbContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Agua Coin Ui",
  description: "Generated by create next app",
  icons: {
    icon: "/Agua-newlogo.png", // <-- ✅ Add this line for favicon.ico
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <BreadcrumbProvider>
            <ToastProvider>
              <LoadingProvider>
                <AuthProvider>
                  <WalletProvider>{children}</WalletProvider>
                </AuthProvider>
              </LoadingProvider>
            </ToastProvider>
          </BreadcrumbProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

// if (!user || user.role !== 'admin') redirect('/login')
